// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCINkY4rAht0ZIIWnmnk3Ife58htHnDVdQ',
    appId: '1:79265919832:android:50435ac5e7fa12752a6b2d',
    messagingSenderId: '79265919832',
    projectId: 'fir-analytics-testapp-e6274',
    storageBucket: 'fir-analytics-testapp-e6274.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPh7-kk6l82o3j7pxzOyWQSLF9-tGy6sw',
    appId: '1:79265919832:ios:0fcf65c9c786b5ff2a6b2d',
    messagingSenderId: '79265919832',
    projectId: 'fir-analytics-testapp-e6274',
    storageBucket: 'fir-analytics-testapp-e6274.appspot.com',
    androidClientId: '79265919832-5b4da028n21dudget9o9r0fcrl7t565j.apps.googleusercontent.com',
    iosClientId: '79265919832-mgmeqt2en71h8m9iq7t1f29h5acambsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAnalyticsTestApp',
  );
}
